github: build images on release
inspirehep/inspirehep pull request #1744
Opened 2021-03-08 11:27 UTC by drjova

2021-03-09 15:40 UTC, benjamin-bergia requested changes

2021-03-09 15:40 UTC, benjamin-bergia commented on .github/workflows/integration.yml
> +  MASTER: ${{ github.event.pull_request.head.sha || github.sha }}
You don't seem to be using this anywhere
```suggestion
```

2021-03-09 15:40 UTC, benjamin-bergia commented on .github/workflows/integration.yml
> +          ui_tag=${{ needs.ui_build.result == 'skipped' && 'master' || env.REF_TAG }}
I would remove this and add:
`BACKEND_IMAGE`, `UI_IMAGE` and `EDITOR_IMAGE` to the **workflow** env. so we can reuse it in the steps where we start the containers.

2021-03-09 15:43 UTC, benjamin-bergia commented on .github/workflows/integration.yml
> +          pull-tag: ${{ matrix.images.version }}
images doesn't have a version field

2021-03-09 15:44 UTC, benjamin-bergia commented on .github/workflows/integration.yml
> +          echo '::set-output name=images::'$json
You are probably better off hardcoding the json here

2021-03-09 15:50 UTC, benjamin-bergia commented
Just to recap because I think it's currently wrong on this PR. Here is the tags we want:
- For the image that have been built in this workflow:
  - `ref-*`
  - `master`
  - `latest`
  - `build-latest` only ig they have a build stage
- For all the images used in the workflow even if not built
  - `master-*`

2021-03-10 08:57 UTC, drjova commented
@benjamin-bergia updated

2021-03-10 10:33 UTC, benjamin-bergia approved these changes

2021-03-10 11:20 UTC, merged