make data citable
inspirehep/inspirehep pull request #3339
Opened 2024-12-16 14:42 UTC by PascalEgn

ref: https://github.com/cern-sis/issues-inspire/issues/598

2025-01-16 15:45 UTC, ioannistsanaktsidis requested changes
Some comments on the UI part

2025-01-16 15:45 UTC, ioannistsanaktsidis commented on ui/src/data/components/DataItem.jsx
> +          {citationCount != null && (
you can just do 
```
citationCount ? <IncomingLiteratureReferencesLinkAction> : <></>
```

2025-01-16 15:45 UTC, ioannistsanaktsidis commented on ui/src/data/components/__tests__/DataItem.test.jsx
> +      citation_count: 666
👿

2025-01-16 15:45 UTC, ioannistsanaktsidis commented on ui/src/data/containers/DetailPageContainer/DetailPageContainer.tsx
> +                {citationCount != null && (
Same here

2025-01-16 15:45 UTC, ioannistsanaktsidis commented on ui/src/data/containers/DetailPageContainer/__tests__/DetailPageContainer.test.jsx
> +    const store = getStoreWithState({
Better use getStore instead of getStoreWithState. getStoreWithState should be removed

2025-01-16 16:12 UTC, drjova commented
thanks @ioannistsanaktsidis fixed

2025-01-16 16:17 UTC, ioannistsanaktsidis commented on backend/inspirehep/records/api/data.py
> +        record.update_authors_records_table()
I am a bit confused with this one. Why we need to update the authors one here ?

2025-01-16 16:20 UTC, drjova commented on backend/inspirehep/records/api/data.py
> +        record.update_authors_records_table()
good question, because we want to display data records in author profiles

2025-01-16 16:22 UTC, ioannistsanaktsidis approved these changes
Looks good to me

2025-01-17 08:56 UTC, PascalEgn commented on ui/src/data/utils.ts
If we change the logic of the function (from getting linked papers to getting papers that reference that data record) we should also change its name, maybe `getReferencingPapersQueryString`

2025-01-17 08:59 UTC, PascalEgn commented on ui/src/data/utils.ts
>  export function getPapersQueryString(recordId: number) {
Dont know if the name is so great, if we change the logic of the function (from getting linked papers to getting papers that reference that data record) we should also change its name, maybe `getReferencingPapersQueryString`

2025-01-17 09:00 UTC, PascalEgn reviewed
I cant approve as i'm a co-author but other than the function name (which can be discussed), looks good to me :)

2025-01-17 10:37 UTC, drjova commented
@PascalEgn done

2025-01-20 12:25 UTC, merged